### ISSUE TITLE
Conditionally switch between using the backport vs the __future__ import

### ISSUE THREAD

**Issue by blazing-gig** [asottile/future-annotations#13]
Hey, 

I recently ran into this issue where I was trying to use this backport in my python package which currently supports python versions 3.6+. 

For versions 3.7+, I'll be using the `from __future__ import annotations` and for 3.6, I'll need to add the encoding line. 

A problem occurs when I try to conditionally add either. 

```py
import sys
if sys.version_info >= (3, 7):
    from __future__ import annotations
else:
    import future_annotations
    future_annotations.register()
```

The problem with the above code is that all `__future__` imports are supposed to be at the top of the file (so does the encoding line). 

Is there a clean way to conditionally switch between using the backport vs the `__future__` import ?

**Comment by asottile** [comment]
you cannot have code before a true `__future__` import and the way this library works is with an encoding cookie which also cannot appear anywhere after the second line (the first line being a shebang)

so the answer is no

**Comment by blazing-gig** [comment]
Hey @asottile , 

If it's not possible to switch conditionally, the only soln I can think of is to use this backport across all python versions or drop support for python3.6 and completely switch to using the `__future__` based import. 

The above soln doesn't seem very convincing. Is there a better workaround ?

**Comment by asottile** [comment]
if there was why do you think it wouldn't be documented?
