### ISSUE TITLE
Pythonista

### ISSUE THREAD

**Issue by denikryt** [asottile/future-annotations#15]
Hi! 
I tried to use your wrapper in Pythonista for my code. The simple way with the encoding cookie at the top of code didn't work for me and I don't understand how to use correctly manual registration. 
I have the main.py file, which have 
_from _future_ import annotations_ 
line at the top and 
_if '__name__' == '__main__':_
at the bottom. 
Also I have several imported modules, which have annotations imports too. 
I don't understand what the **_actual_main_** is from the example. 
How to use correctly manual registration?
Thank you!

**Comment by asottile** [comment]
I don't think Pythonista is set up to work with generic third party dependencies
